### ISSUE TITLE
Ioni example Crash 

### ISSUE THREAD

**Issue by hacktar** [mariusbackes/cordova-plugin-sumup#8]
Ioni example crash executing pay (and settings), has anyone managed to make the pay work in the ionic example?

**Comment by swarnendu22** [comment]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object toothpick.Scope.getInstance(java.lang.Class)' on a null object reference
        at com.sumup.merchant.CoreState.get(SourceFile:451)
        at de.mariusbackes.cordova.sumup.SumUp.lambda$auth$2$SumUp(SumUp.java:148)

Getting this issue

**Comment by Cirilord** [comment]
Me too

**Comment by chadmulligan** [comment]
Probably the same I am facing when calling `isLoggedIn()` the first time : `Attempt to invoke virtual method 'java.lang.Object com.sumup.merchant.CoreState.get(java.lang.Class)' on a null object reference`

Guess it's coming from the plugin initialization.

**Comment by abutizi** [comment]
Did you guys managed to find a solution for this?
Care to share?

**Comment by abutizi** [comment]
Seems like the crash happens at this line in the Java file:
cordova.getActivity().runOnUiThread(runnable);
But I just do not know what to change. Any help will be a great chrismas present :D

**Comment by petermeester** [comment]
Hi @abutizi,

What is your setup? On which device are you experiencing this?

Regards,
Peter

**Comment by abutizi** [comment]
Hi @petermeester 

Thank you for your reply. I'm experiencing this using Android tablet with IONIC.
When observing logcat, I get the following error:

`
02-05 14:03:43.779 22428 26147 E PluginManager: Uncaught exception from plugin
02-05 14:03:43.779 22428 26147 E PluginManager: java.lang.NullPointerException: Attempt to invoke virtual method 'com.sumup.merchant.Models.UserDetails$Business com.sumup.merchant.Models.UserDetails.getBusiness()' on a null object reference
02-05 14:03:43.779 22428 26147 E PluginManager:         at com.sumup.merchant.Models.UserModel.getBusiness(SourceFile:316)
02-05 14:03:43.779 22428 26147 E PluginManager:         at com.sumup.merchant.Models.UserModel.getMerchantCode(SourceFile:320)
02-05 14:03:43.779 22428 26147 E PluginManager:         at com.sumup.merchant.api.SumUpAPI.getCurrentMerchant(SourceFile:209)
02-05 14:03:43.779 22428 26147 E PluginManager:         at de.mariusbackes.cordova.sumup.SumUp.pay(SumUp.java:352)
02-05 14:03:43.779 22428 26147 E PluginManager:         at de.mariusbackes.cordova.sumup.SumUp.execute(SumUp.java:106)
02-05 14:03:43.779 22428 26147 E PluginManager:         at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
02-05 14:03:43.779 22428 26147 E PluginManager:         at org.apache.cordova.PluginManager.exec(PluginManager.java:139)
02-05 14:03:43.779 22428 26147 E PluginManager:         at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
02-05 14:03:43.779 22428 26147 E PluginManager:         at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
02-05 14:03:43.779 22428 26147 E PluginManager:         at android.os.MessageQueue.nativePollOnce(Native Method)
02-05 14:03:43.779 22428 26147 E PluginManager:         at android.os.MessageQueue.next(MessageQueue.java:335)
02-05 14:03:43.779 22428 26147 E PluginManager:         at android.os.Looper.loop(Looper.java:207)
02-05 14:03:43.779 22428 26147 E PluginManager:         at android.os.HandlerThread.run(HandlerThread.java:67)
`

Could it be because I am using a test/dev/sandbox account?
